### ISSUE TITLE
nested folders commit might have broken dropbox backup

### ISSUE THREAD

**Issue by tanyav1995** [bsnacks000/datascience-project#6]
push-to-dropbox -n rtm_unc_new
uploading...  //home/tanya/ds-projects/rtm-unc-new/data/.gitignore
Traceback (most recent call last):
  File "/home/tanya/ds-projects/rtm-unc-new/venv/bin/push-to-dropbox", line 11, in <module>
    load_entry_point('rtm-unc-new', 'console_scripts', 'push-to-dropbox')()
  File "/home/tanya/ds-projects/rtm-unc-new/venv/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/tanya/ds-projects/rtm-unc-new/venv/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/tanya/ds-projects/rtm-unc-new/venv/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/tanya/ds-projects/rtm-unc-new/venv/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/tanya/ds-projects/rtm-unc-new/_rtm_unc_new_build_system/dropbox_api.py", line 125, in push_to_dropbox
    client.upload_data()
  File "/home/tanya/ds-projects/rtm-unc-new/_rtm_unc_new_build_system/dropbox_api.py", line 83, in upload_data
    res = self._dbx.files_upload(f.read(), dbx_path)
  File "/home/tanya/ds-projects/rtm-unc-new/venv/lib/python3.6/site-packages/dropbox/base.py", line 2963, in files_upload
    f,
  File "/home/tanya/ds-projects/rtm-unc-new/venv/lib/python3.6/site-packages/dropbox/dropbox.py", line 338, in request
    user_message_locale)
dropbox.exceptions.ApiError: ApiError('f029dec068ad266ad6fc5a02ed46675c', UploadError('path', UploadWriteFailed(reason=WriteError('malformed_path', None), upload_session_id='AAAAAAAAHYCXGIAOiWqoKw')))
Makefile:44: recipe for target 'push-to-dropbox' failed
make: *** [push-to-dropbox] Error 1

**Comment by bsnacks000** [comment]
Should fix the malformed path issue... b26fc09
Not sure how this got out of sync with the test-build I was working off of but I think this logic should hold for any nested path with any local-path name
